version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parser
    ports:
      - "5432:5432"
    networks:
      - parser_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  parser:
    build: ./script
    container_name: parser
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: 'parser'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST: db
    command: ["python", "first.py"]
    networks:
      - parser_network

volumes:
  db_data:

networks:
  parser_network:
    driver: bridge
